import React from "react";

const Users = [
  {
    login: "Milos",
    id: 1482759,
    node_id: "MDQ6VXNlcjE0ODI3NTk=",
    avatar_url: "https://avatars.githubusercontent.com/u/1482759?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Milos",
    html_url: "https://github.com/Milos",
    followers_url: "https://api.github.com/users/Milos/followers",
    following_url: "https://api.github.com/users/Milos/following{/other_user}",
    gists_url: "https://api.github.com/users/Milos/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Milos/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Milos/subscriptions",
    organizations_url: "https://api.github.com/users/Milos/orgs",
    repos_url: "https://api.github.com/users/Milos/repos",
    events_url: "https://api.github.com/users/Milos/events{/privacy}",
    received_events_url: "https://api.github.com/users/Milos/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "h3h394",
    id: 43048578,
    node_id: "MDQ6VXNlcjQzMDQ4NTc4",
    avatar_url: "https://avatars.githubusercontent.com/u/43048578?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/h3h394",
    html_url: "https://github.com/h3h394",
    followers_url: "https://api.github.com/users/h3h394/followers",
    following_url: "https://api.github.com/users/h3h394/following{/other_user}",
    gists_url: "https://api.github.com/users/h3h394/gists{/gist_id}",
    starred_url: "https://api.github.com/users/h3h394/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/h3h394/subscriptions",
    organizations_url: "https://api.github.com/users/h3h394/orgs",
    repos_url: "https://api.github.com/users/h3h394/repos",
    events_url: "https://api.github.com/users/h3h394/events{/privacy}",
    received_events_url: "https://api.github.com/users/h3h394/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "Al-assad",
    id: 22493821,
    node_id: "MDQ6VXNlcjIyNDkzODIx",
    avatar_url: "https://avatars.githubusercontent.com/u/22493821?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Al-assad",
    html_url: "https://github.com/Al-assad",
    followers_url: "https://api.github.com/users/Al-assad/followers",
    following_url:
      "https://api.github.com/users/Al-assad/following{/other_user}",
    gists_url: "https://api.github.com/users/Al-assad/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Al-assad/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Al-assad/subscriptions",
    organizations_url: "https://api.github.com/users/Al-assad/orgs",
    repos_url: "https://api.github.com/users/Al-assad/repos",
    events_url: "https://api.github.com/users/Al-assad/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Al-assad/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "milosgajdos",
    id: 1392526,
    node_id: "MDQ6VXNlcjEzOTI1MjY=",
    avatar_url: "https://avatars.githubusercontent.com/u/1392526?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/milosgajdos",
    html_url: "https://github.com/milosgajdos",
    followers_url: "https://api.github.com/users/milosgajdos/followers",
    following_url:
      "https://api.github.com/users/milosgajdos/following{/other_user}",
    gists_url: "https://api.github.com/users/milosgajdos/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/milosgajdos/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/milosgajdos/subscriptions",
    organizations_url: "https://api.github.com/users/milosgajdos/orgs",
    repos_url: "https://api.github.com/users/milosgajdos/repos",
    events_url: "https://api.github.com/users/milosgajdos/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/milosgajdos/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "MilosKozak",
    id: 11146458,
    node_id: "MDQ6VXNlcjExMTQ2NDU4",
    avatar_url: "https://avatars.githubusercontent.com/u/11146458?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MilosKozak",
    html_url: "https://github.com/MilosKozak",
    followers_url: "https://api.github.com/users/MilosKozak/followers",
    following_url:
      "https://api.github.com/users/MilosKozak/following{/other_user}",
    gists_url: "https://api.github.com/users/MilosKozak/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MilosKozak/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MilosKozak/subscriptions",
    organizations_url: "https://api.github.com/users/MilosKozak/orgs",
    repos_url: "https://api.github.com/users/MilosKozak/repos",
    events_url: "https://api.github.com/users/MilosKozak/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MilosKozak/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "MilosSimic",
    id: 4248569,
    node_id: "MDQ6VXNlcjQyNDg1Njk=",
    avatar_url: "https://avatars.githubusercontent.com/u/4248569?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MilosSimic",
    html_url: "https://github.com/MilosSimic",
    followers_url: "https://api.github.com/users/MilosSimic/followers",
    following_url:
      "https://api.github.com/users/MilosSimic/following{/other_user}",
    gists_url: "https://api.github.com/users/MilosSimic/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MilosSimic/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MilosSimic/subscriptions",
    organizations_url: "https://api.github.com/users/MilosSimic/orgs",
    repos_url: "https://api.github.com/users/MilosSimic/repos",
    events_url: "https://api.github.com/users/MilosSimic/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MilosSimic/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "milostosic",
    id: 1654399,
    node_id: "MDQ6VXNlcjE2NTQzOTk=",
    avatar_url: "https://avatars.githubusercontent.com/u/1654399?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/milostosic",
    html_url: "https://github.com/milostosic",
    followers_url: "https://api.github.com/users/milostosic/followers",
    following_url:
      "https://api.github.com/users/milostosic/following{/other_user}",
    gists_url: "https://api.github.com/users/milostosic/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/milostosic/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/milostosic/subscriptions",
    organizations_url: "https://api.github.com/users/milostosic/orgs",
    repos_url: "https://api.github.com/users/milostosic/repos",
    events_url: "https://api.github.com/users/milostosic/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/milostosic/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "milos-agathon",
    id: 37574511,
    node_id: "MDQ6VXNlcjM3NTc0NTEx",
    avatar_url: "https://avatars.githubusercontent.com/u/37574511?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/milos-agathon",
    html_url: "https://github.com/milos-agathon",
    followers_url: "https://api.github.com/users/milos-agathon/followers",
    following_url:
      "https://api.github.com/users/milos-agathon/following{/other_user}",
    gists_url: "https://api.github.com/users/milos-agathon/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/milos-agathon/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/milos-agathon/subscriptions",
    organizations_url: "https://api.github.com/users/milos-agathon/orgs",
    repos_url: "https://api.github.com/users/milos-agathon/repos",
    events_url: "https://api.github.com/users/milos-agathon/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/milos-agathon/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
];

export default Users;